# Workflow name
name: CI/CD Pipeline

on:
  # Manually trigger workflow runs
  workflow_dispatch:
  # Trigger the workflow on push from the main branch
  push:
    branches:
      - main

jobs:
  # Test job
  tests:
    name: Unit tests
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest

    # Job steps
    steps:
      # Check out your repository under $GITHUB_WORKSPACE
      - name: Check out code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Maven cache
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Run Tests
      - name: Run Tests
        run: mvn -B test

  # Deploy job
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: tests  # Ejecuta este job solo si los tests son exitosos

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          # Crear un nuevo paquete de aplicación
          zip -r deployment.zip target/*.jar
          # Subir el paquete de la aplicación a Elastic Beanstalk
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.AWS_EB_APP_NAME }} \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=my-bucket,S3Key=deployment.zip
          # Desplegar la nueva versión en el entorno
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.AWS_EB_ENV_NAME }} \
            --version-label $GITHUB_SHA
